# Dada Ki Jay Ho

version: '3'


services:
  redis-db:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    command: /bin/sh -c "redis-server --requirepass root"

volumes:
  redis_data: