# Dada Ki Jay Ho

version: '3'


services:
  redis-db:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    command: /bin/sh -c "redis-server --requirepass root"
  
  postgres:
    image: postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test
    # volumes:
    #   - ./data:/var/lib/postgresql/data  

volumes:
  redis_data: